//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyProjectSM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class foodiesEntities1 : DbContext
    {
        public foodiesEntities1()
            //: base("name=dapr.cgxhizvygbdd.us-east-2.rds.amazonaws.com")
            : base("name=foodiesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<DaPrUser> DaPrUsers { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
    }
}
